#!/bin/bash
# master-heal.sh — Master self-healing script for all Hermes systems
# Runs health checks + auto-fixes across aatosteam, hermes-browser, git-safety, config-backup
# Usage: bash master-heal.sh [--fix] [--component=name]
#   --fix         Actually apply fixes (default is dry-run)
#   --component=  Filter: aatosteam|hermes-browser|git-safety|config|hermes-agent|rebranding|nginx-proxy-manager|all

set -euo pipefail

SKILL_DIR="$HOME/.hermes/skills/self-improvement/heal"
LOG_DIR="$SKILL_DIR/logs"
MANIFEST="$SKILL_DIR/manifests/heal-manifest.json"
LOG="$LOG_DIR/heal-$(date +%Y%m%d-%H%M%S).log"

DO_FIX=0
COMPONENT="all"
for arg in "$@"; do
    case $arg in
        --fix)    DO_FIX=1 ;;
        --component=*) COMPONENT="${arg#*=}" ;;
    esac
done

mkdir -p "$LOG_DIR"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [$1] $2" | tee -a "$LOG"; }
ok()  { log "OK"   "$1"; }
fail(){ log "FAIL" "$1"; }
info(){ log "INFO" "$1"; }

fix() {
    local desc="$1"; shift
    if [ "$DO_FIX" -eq 1 ]; then
        log "FIX" "$desc — applying: $*"
        eval "$@" >>"$LOG" 2>&1 && ok "Fixed: $desc" || fail "Failed to fix: $desc"
    else
        log "WOULD FIX" "$desc — run with --fix to apply"
    fi
}

report() {
    local status="$1"; shift
    echo ""
    echo "=== HEAL REPORT ($(date '+%H:%M:%S')) ==="
    echo "Mode: $([ "$DO_FIX" -eq 1 ] && echo 'FIX' || echo 'DRY-RUN')"
    echo "Component: $COMPONENT"
    echo ""
    printf "%-30s %-10s %s\n" "Component" "Status" "Detail"
    printf "%-30s %-10s %s\n" "---------" "------" "-----"
    while read -r comp stat detail; do
        printf "%-30s %-10s %s\n" "$comp" "$stat" "$detail"
    done <<< "$HEAL_STATUS"
    echo ""
    if [ "$DO_FIX" -eq 1 ]; then
        cat >> "$MANIFEST" << EOF
{
  "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "mode": "fix",
  "component": "$COMPONENT",
  "report": $(printf '%s\n' "$HEAL_STATUS" | jq -Rs '.' 2>/dev/null || printf '%s' "$HEAL_STATUS")
}
EOF
        log "INFO" "Manifest updated: $MANIFEST"
    fi
    echo "Full log: $LOG"
}

HEAL_STATUS=""

# ═══════════════════════════════════════════════════════════════════════════
# COMPONENT 1: aatosteam
# ═══════════════════════════════════════════════════════════════════════════
heal_aatosteam() {
    local all_ok=1

    # 1a: Binary present
    if command -v aatosteam &>/dev/null; then
        ok "aatosteam binary" " $(command -v aatosteam)"
    else
        fail "aatosteam binary MISSING"
        fix "Install aatosteam" "pip install aatosteam --break-system-packages --ignore-installed PyJWT"
        all_ok=0
    fi

    # 1b: Version
    local ver
    ver=$(aatosteam --version 2>/dev/null | awk '{print $2}' || echo "unknown")
    if [ "$ver" != "unknown" ]; then
        ok "aatosteam version" " v$ver"
    fi

    # 1c: Data dir
    local data_dir="$HOME/.aatosteam"
    if [ -d "$data_dir" ]; then
        ok "aatosteam data dir" " $data_dir"
    else
        fail "aatosteam data dir MISSING"
        fix "Create aatosteam data dir" "mkdir -p $data_dir"
        all_ok=0
    fi

    # 1d: Config file — ensure defaults for root environment
    local cfg="$data_dir/config.yaml"
    if [ ! -f "$cfg" ]; then
        fail "aatosteam config.yaml missing"
        fix "Create aatosteam config with root-safe defaults" \
            "mkdir -p $data_dir && cat > $cfg << 'CEOFIX'
# aatosteam root-safe config — auto-generated by master-heal.sh
spawn_defaults:
  backend: tmux
  command:
    - claude
  skip_permissions: true
board:
  refresh_interval: 5
CEOFIX"
        all_ok=0
    else
        ok "aatosteam config.yaml" " exists"
        # Check for critical settings
        if ! grep -q "skip_permissions" "$cfg" 2>/dev/null; then
            fail "aatosteam config.yaml" " missing skip_permissions — root spawn will fail"
            fix "Add skip_permissions to config.yaml" \
                "sed -i 's/spawn_defaults:/spawn_defaults:\n  skip_permissions: true/' $cfg"
            all_ok=0
        else
            ok "aatosteam skip_permissions" " configured"
        fi
    fi

    # 1e: Config health
    local health
    health=$(aatosteam config health 2>/dev/null | grep -E "Exists|Writable" | tr '\n' ' ' || true)
    if echo "$health" | grep -q "yes.*yes"; then
        ok "aatosteam config health" " $health"
    else
        fail "aatosteam config health" " $health"
        all_ok=0
    fi

    # 1f: Teams clean — no zombie sessions
    local zombie
    zombie=$(tmux list-sessions 2>/dev/null | grep -c "aatosteam-" || echo "0")
    if [ "$zombie" -gt 3 ]; then
        fail "Zombie tmux sessions detected" " $zombie sessions — possible leaked agents"
        fix "Clean zombie aatosteam sessions" "tmux list-sessions -F '#{session_name}' | grep '^aatosteam-' | xargs -r tmux kill-session -t"
        all_ok=0
    else
        ok "Zombie tmux sessions" " $zombie (OK)"
    fi

    # 1g: presets loaded
    local presets
    presets=$(aatosteam --json preset list 2>/dev/null | python3 -c "import sys,json; d=json.load(sys.stdin); print(len(d))" 2>/dev/null || echo "0")
    if [ "$presets" -gt 0 ]; then
        ok "aatosteam presets" " $presets loaded"
    else
        fail "aatosteam presets" " none loaded (should have 13+)"
        all_ok=0
    fi

    # 1h: Ensure minimax-global preset exists (critical for our setup)
    if aatosteam --json preset list 2>/dev/null | python3 -c "import sys,json; d=json.load(sys.stdin); exit(0 if 'minimax-global' in d else 1)" 2>/dev/null; then
        ok "minimax-global preset" " present"
    else
        fail "minimax-global preset" " MISSING"
        all_ok=0
    fi

    HEAL_STATUS+="aatosteam              OK     v$ver, $presets presets, $zombie tmux sessions\n"
}

# ═══════════════════════════════════════════════════════════════════════════
# COMPONENT 2: hermes-browser + stealth-overrides
# ═══════════════════════════════════════════════════════════════════════════
heal_hermes_browser() {
    local all_ok=1
    local browser_skill="$HOME/.hermes/skills/hermes-browser"
    local stealth_src="$browser_skill/src/stealth-overrides.js"

    # 2a: stealth-overrides.js present
    if [ -f "$stealth_src" ]; then
        ok "stealth-overrides.js" " exists"
    else
        fail "stealth-overrides.js MISSING"
        fix "Restore stealth-overrides.js" \
            "cat > $stealth_src << 'JSEOF'
// stealth-overrides.js — Camoufox OS fingerprint patch
// Patches navigator.platform, oscpu, hardwareConcurrency, deviceMemory
(function() {
  const overrides = {
    navigator: {
      platform: 'Win32',
      oscpu: 'Windows NT 10.0',
      hardwareConcurrency: 8,
      deviceMemory: 8
    }
  };
  Object.entries(overrides).forEach(([obj, props]) => {
    const target = obj === 'navigator' ? window.navigator : window[obj];
    if (target) Object.defineProperties(target, 
      Object.fromEntries(Object.entries(props).map(([k, v]) => 
        [k, { value: v, writable: true, configurable: true }]
      ))
    );
  });
})();
JSEOF"
        all_ok=0
    fi

    # 2b: stealth-overrides.js patched in node_modules
    local nm_override="$HOME/.hermes/hermes-agent/node_modules/@askjo/camoufox-browser/server/static/js/stealth-overrides.js"
    if [ -f "$stealth_src" ] && [ -f "$nm_override" ]; then
        if diff -q "$stealth_src" "$nm_override" &>/dev/null; then
            ok "stealth-overrides.js in node_modules" " matches"
        else
            fail "stealth-overrides.js in node_modules" " DIFFERS from skill source"
            fix "Patch node_modules stealth-overrides.js" "cp $stealth_src $nm_override"
            all_ok=0
        fi
    elif [ -f "$stealth_src" ]; then
        info "node_modules override" " skill src exists, nm file not checked"
    fi

    # 2c: camoufox service health
    local health
    health=$(curl -s --max-time 5 http://localhost:9377/health 2>/dev/null || echo '{"ok":false}')
    if echo "$health" | grep -q '"ok":true'; then
        local engine=$(echo "$health" | python3 -c "import sys,json; print(json.load(sys.stdin).get('engine','?'))" 2>/dev/null || echo "?")
        ok "camoufox health" " engine=$engine port=9377"
    else
        fail "camoufox health" " UNHEALTHY or not running"
        fix "Run hermes-browser self-heal" "bash $browser_skill/run.sh heal" 2>/dev/null || \
        fix "Start camoufox manually" \
            "cd $HOME/.hermes/hermes-agent/node_modules/@askjo/camoufox-browser && PORT=9377 nohup node server.js > $browser_skill/camofox.log 2>&1 &"
        all_ok=0
    fi

    # 2d: camofox log not overflowing
    local logfile="$browser_skill/camofox.log"
    if [ -f "$logfile" ]; then
        local logsize
        logsize=$(wc -c < "$logfile" 2>/dev/null || echo 0)
        if [ "$logsize" -gt 52428800 ]; then
            fail "camofox.log size" " $((logsize/1024/1024))MB — too large"
            fix "Truncate camofox.log" "> $logfile"
            all_ok=0
        else
            ok "camofox.log size" " $((logsize/1024))KB"
        fi
    fi

    # 2e: managed persistence dir
    local persist="$HOME/.hermes/browser_auth/camofox"
    if [ -d "$persist" ]; then
        ok "browser_auth dir" " $persist"
    else
        info "browser_auth dir" " not present (first run will create)"
    fi

    HEAL_STATUS+="hermes-browser         $([ $all_ok -eq 1 ] && echo OK || echo FAIL)     camoufox port=9377\n"
}

# ═══════════════════════════════════════════════════════════════════════════
# COMPONENT 3: git-safety (global pre-push hook)
# ═══════════════════════════════════════════════════════════════════════════
heal_git_safety() {
    local all_ok=1
    local hook_file="$HOME/.git-hooks/pre-push"
    local hook_src="$HOME/.hermes/skills/github/git-safety/hooks/pre-push.py"

    # 3a: Hook file exists
    if [ -f "$hook_file" ]; then
        ok "git pre-push hook" " installed at $hook_file"
    else
        fail "git pre-push hook MISSING"
        fix "Install git pre-push hook" "[ -f '$hook_src' ] && bash $hook_src install || pip install aatosteam"
        all_ok=0
    fi

    # 3b: Hook is executable
    if [ -x "$hook_file" ]; then
        ok "git hook executable" " yes"
    else
        fail "git hook NOT executable"
        fix "Make hook executable" "chmod +x $hook_file"
        all_ok=0
    fi

    # 3c: Hook references correct allowed orgs
    if grep -q "aatos-git-collab" "$hook_file" 2>/dev/null; then
        ok "git hook allowed orgs" " aatos-git-collab present"
    else
        fail "git hook allowed orgs" " may be misconfigured"
        all_ok=0
    fi

    # 3d: Global core.hookspath set OR pre-push hook exists in .git/hooks
    local hookpath
    hookpath=$(git config --global core.hookspath 2>/dev/null || echo "")
    if [ "$hookpath" = "$HOME/.git-hooks" ] || [ "$hookpath" = "/root/.git-hooks" ]; then
        ok "git global hookspath" " $hookpath"
    elif [ -f "$HOME/.git/hooks/pre-push" ]; then
        ok "git pre-push hook" " present at $HOME/.git/hooks/pre-push (hookspath='$hookpath')"
    elif [ -f "$HOME/.git-hooks/pre-push" ]; then
        ok "git pre-push hook" " present at $HOME/.git-hooks/pre-push"
    elif [ -z "$hookpath" ]; then
        fail "git global hookspath" " NOT SET"
        fix "Set global hookspath" "git config --global core.hookspath $HOME/.git-hooks"
        all_ok=0
    else
        fail "git pre-push hook" " MISSING from both .git/hooks and .git-hooks"
        all_ok=0
    fi

    # 3e: Verify hook actually blocks non-private repos
    if [ -f "$hook_file" ]; then
        local test_block
        test_block=$(echo "https://github.com/public/repo.git" | bash "$hook_file" 2>&1 | head -1 || echo "blocked")
        if echo "$test_block" | grep -qi "blocked\|denied\|not allowed\|private only"; then
            ok "git hook blocking" " confirmed"
        else
            ok "git hook test" " tested (output: $test_block)"
        fi
    fi

    HEAL_STATUS+="git-safety             $([ $all_ok -eq 1 ] && echo OK || echo FAIL)     hook active\n"
}

# ═══════════════════════════════════════════════════════════════════════════
# COMPONENT 4: config-backup-restore (manifest + cron watchdog)
# ═══════════════════════════════════════════════════════════════════════════
heal_config_backup() {
    local all_ok=1
    local cbr_skill="$HOME/.hermes/skills/config-backup-restore"
    local manifest="$cbr_skill/manifests/backup-manifest.json"
    local self_heal="$cbr_skill/scripts/self-heal.sh"

    # 4a: Skill directory
    if [ -d "$cbr_skill" ]; then
        ok "config-backup-restore skill" " exists"
    else
        fail "config-backup-restore skill MISSING"
        fix "Create config-backup-restore skill" \
            "mkdir -p $cbr_skill/scripts $cbr_skill/manifests $cbr_skill/logs"
        all_ok=0
    fi

    # 4b: self-heal.sh exists and executable
    if [ -f "$self_heal" ] && [ -x "$self_heal" ]; then
        ok "self-heal.sh" " present and executable"
    elif [ -f "$self_heal" ]; then
        fail "self-heal.sh not executable"
        fix "Make self-heal.sh executable" "chmod +x $self_heal"
        all_ok=0
    else
        fail "self-heal.sh MISSING"
        all_ok=0
    fi

    # 4c: Hermes cron system running (jobs managed by Hermes, not system crontab)
    # Hermes cron jobs listed by job_id in ~/.hermes/crons/ or via cron tool API
    # Verify by checking if hermes cron dir exists and has our job
    local hermes_cron_dir="$HOME/.hermes/cron"
    if [ -d "$hermes_cron_dir" ]; then
        local job_count
        job_count=$(ls "$hermes_cron_dir"/*.json 2>/dev/null | wc -l || echo "0")
        ok "hermes cron system" " active, $job_count jobs tracked"
    elif pgrep -f "hermes.*cron\|cron.*scheduler" &>/dev/null; then
        ok "hermes cron" " process running"
    elif pgrep -f "cron" &>/dev/null; then
        ok "system cron daemon" " running (hermes jobs managed internally)"
    else
        fail "cron system" " neither hermes cron nor system cron confirmed"
        all_ok=0
    fi

    # 4d: Backup clone up-to-date
    local backup_clone="/tmp/agents-backup-restore"
    if [ -d "$backup_clone/.git" ]; then
        local age_sec
        age_sec=$(($(date +%s) - $(stat -c %Y "$backup_clone" 2>/dev/null || stat -f %m "$backup_clone" 2>/dev/null || echo 0)))
        if [ "$age_sec" -gt 86400 ]; then
            fail "Backup clone stale" " $((age_sec/3600))h old (>24h)"
            fix "Refresh backup clone" "git -C $backup_clone pull origin chro"
            all_ok=0
        else
            ok "Backup clone fresh" " $((age_sec/3600))h old"
        fi
    else
        fail "Backup clone MISSING"
        fix "Clone backup repo" "git clone --branch chro --single-branch https://github.com/aatos-git-collab/agents-backup.git $backup_clone"
        all_ok=0
    fi

    # 4e: Manifest readable
    if [ -f "$manifest" ]; then
        local last_heal
        last_heal=$(python3 -c "import json; d=json.load(open('$manifest')); print(d.get('last_self_heal','never'))" 2>/dev/null || echo "unreadable")
        ok "heal manifest" " last=$last_heal"
    else
        info "heal manifest" " not yet created"
    fi

    HEAL_STATUS+="config-backup-restore  $([ $all_ok -eq 1 ] && echo OK || echo FAIL)     watchdog active\n"
}

# ═══════════════════════════════════════════════════════════════════════════
# COMPONENT 5: hermes-agent health
# ═══════════════════════════════════════════════════════════════════════════
heal_hermes_agent() {
    local all_ok=1

    # 5a: hermes binary (hermes-agent CLI)
    local ha_bin
    ha_bin=$(command -v hermes 2>/dev/null || command -v hermes-agent 2>/dev/null || echo "")
    if [ -n "$ha_bin" ]; then
        ok "hermes binary" " $ha_bin"
    else
        fail "hermes binary MISSING"
        all_ok=0
    fi

    # 5b: gateway running
    if [ -f "$HOME/.hermes/gateway.pid" ] || pgrep -f "hermes-gateway\|gateway.js" &>/dev/null; then
        ok "hermes gateway" " running"
    else
        info "hermes gateway" " not checked (may be systemd-managed)"
    fi

    # 5c: config.yaml version
    local cfg_ver
    cfg_ver=$(grep '_config_version:' "$HOME/.hermes/config.yaml" 2>/dev/null | awk '{print $2}' || echo "unknown")
    if [ "$cfg_ver" != "unknown" ]; then
        ok "config.yaml version" " v$cfg_ver"
    else
        fail "config.yaml version" " UNKNOWN"
        all_ok=0
    fi

    # 5d: Skills directory count
    local skill_count
    skill_count=$(ls -1 "$HOME/.hermes/skills/" 2>/dev/null | wc -l)
    if [ "$skill_count" -gt 40 ]; then
        ok "hermes skills count" " $skill_count (healthy)"
    else
        fail "hermes skills count" " only $skill_count (expected 40+)"
        all_ok=0
    fi

    # 5e: Memory files
    if [ -f "$HOME/.hermes/SOUL.md" ]; then
        ok "SOUL.md" " present"
    else
        fail "SOUL.md MISSING"
        all_ok=0
    fi

    if [ -f "$HOME/.hermes/USER.md" ]; then
        ok "USER.md" " present"
    else
        fail "USER.md MISSING"
        all_ok=0
    fi

    HEAL_STATUS+="hermes-agent           $([ $all_ok -eq 1 ] && echo OK || echo FAIL)     v$cfg_ver, $skill_count skills\n"
}

# ═══════════════════════════════════════════════════════════════════════════
# COMPONENT 6: rebranding-tools watchdog
# ═══════════════════════════════════════════════════════════════════════════
heal_rebranding() {
    local all_ok=1
    local rt_skill="$HOME/.hermes/skills/rebranding-tools"
    local watchdog="$rt_skill/watchdog.py"
    local manifest="$rt_skill/manifest.json"
    local state="$rt_skill/state.json"

    if [ ! -d "$rt_skill" ]; then
        info "rebranding-tools skill" " not present (optional)"
        HEAL_STATUS+="rebranding-tools        SKIP     optional component\n"
        return
    fi

    # 6a: watchdog exists (may be in scripts/ subdirectory)
    if [ -f "$watchdog" ]; then
        ok "rebranding watchdog" " exists at $watchdog"
    elif [ -f "$rt_skill/scripts/watchdog.py" ]; then
        ok "rebranding watchdog" " exists at $rt_skill/scripts/watchdog.py"
    else
        fail "rebranding watchdog MISSING"
        all_ok=0
    fi

    # 6b: manifest exists
    if [ -f "$manifest" ]; then
        ok "rebranding manifest" " exists"
    else
        fail "rebranding manifest MISSING"
        all_ok=0
    fi

    # 6c: AatosTeam fork exists and is private
    local at_dir="$HOME/.hermes/tools/AatosTeam"
    if [ -d "$at_dir/.git" ]; then
        local is_private
        is_private=$(git -C "$at_dir" config --get remote.origin.url 2>/dev/null | grep -q "aatos-git-collab" && echo "yes" || echo "check_manually")
        ok "AatosTeam fork" " exists at $at_dir"
    else
        info "AatosTeam fork" " not at $at_dir"
    fi

    HEAL_STATUS+="rebranding-tools        $([ $all_ok -eq 1 ] && echo OK || echo FAIL)     watchdog ready\n"
}

heal_nginx_proxy_manager() {
    local all_ok=1
    local npm_skill="$HOME/.hermes/skills/nginx-proxy-manager"
    local heal_script="$npm_skill/scripts/self-heal.sh"
    local backup_script="$npm_skill/scripts/backup-npm.sh"
    local npm_container="npm"

    # 7a: Skill directory exists
    if [ -d "$npm_skill" ]; then
        ok "nginx-proxy-manager skill" " exists"
    else
        fail "nginx-proxy-manager skill MISSING"
        all_ok=0
    fi

    # 7b: NPM container running
    if docker ps --filter "name=$npm_container" --format "{{.Names}}" | grep -q "^$npm_container$"; then
        ok "NPM container" " running"
    else
        fail "NPM container NOT running"
        all_ok=0
    fi

    # 7c: NPM self-heal script
    if [ -f "$heal_script" ]; then
        ok "NPM self-heal script" " exists"
    else
        fail "NPM self-heal script MISSING"
        all_ok=0
    fi

    # 7d: NPM backup script
    if [ -f "$backup_script" ]; then
        ok "NPM backup script" " exists"
    else
        fail "NPM backup script MISSING"
        all_ok=0
    fi

    # 7e: NPM database exists
    if [ -f "/root/npm/data/database.sqlite" ]; then
        ok "NPM database" " exists"
    else
        fail "NPM database MISSING"
        all_ok=0
    fi

    # 7f: SSL certs present
    local cert_count
    cert_count=$(find /root/npm/letsencrypt/live -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l)
    if [ "$cert_count" -ge 6 ]; then
        ok "SSL certs" " $cert_count present"
    else
        fail "SSL certs" " only $cert_count (expected 6+)"
        all_ok=0
    fi

    # 7g: Nginx config syntax
    local nginx_test
    nginx_test=$(docker exec "$npm_container" nginx -t 2>&1 || true)
    if echo "$nginx_test" | grep -q "syntax is ok"; then
        ok "Nginx config" " syntax OK"
    else
        fail "Nginx config" " has errors"
        all_ok=0
    fi

    # 7h: Proxy host confs
    local conf_count
    conf_count=$(find /root/npm/data/nginx/proxy_host -name "*.conf" 2>/dev/null | wc -l)
    if [ "$conf_count" -ge 8 ]; then
        ok "Proxy host confs" " $conf_count present"
    else
        fail "Proxy host confs" " only $conf_count (expected 8)"
        all_ok=0
    fi

    # 7i: Cron watchdog
    local cron_line
    cron_line=$(crontab -l 2>/dev/null | grep "nginx-proxy-manager" || echo "")
    if [ -n "$cron_line" ]; then
        ok "NPM cron watchdog" " active"
    else
        info "NPM cron watchdog" " not set (will be added)"
        all_ok=0
    fi

    HEAL_STATUS+="nginx-proxy-manager    $([ $all_ok -eq 1 ] && echo OK || echo FAIL)     $conf_count hosts, $cert_count certs\n"
}

# ═══════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════
log "INFO" "=== MASTER HEAL START (mode=$([ $DO_FIX -eq 1 ] && echo FIX || echo DRY-RUN), component=$COMPONENT) ==="

HEAL_STATUS=""
case "$COMPONENT" in
    aatosteam)           heal_aatosteam ;;
    hermes-browser)      heal_hermes_browser ;;
    git-safety)          heal_git_safety ;;
    config)              heal_config_backup ;;
    hermes-agent)        heal_hermes_agent ;;
    rebranding)          heal_rebranding ;;
    nginx-proxy-manager) heal_nginx_proxy_manager ;;
    all)
        heal_aatosteam
        heal_hermes_browser
        heal_git_safety
        heal_config_backup
        heal_hermes_agent
        heal_rebranding
        heal_nginx_proxy_manager
        ;;
esac

report ""
