#!/bin/bash
#===============================================================================
# Git Push Safety Setup Script
# 
# Purpose: Set up multi-layer protection against accidental pushes to 
#          non-aatos repos (upstream sources, public repos, etc.)
#
# Usage:
#   bash git-push-safety.sh           # Interactive
#   bash git-push-safety.sh --silent  # Non-interactive
#   bash git-push-safety.sh --verify  # Just verify existing setup
#
#===============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOOKS_DIR="$HOME/.git-hooks"
HOOK_FILE="$HOOKS_DIR/pre-push"
GLOBAL_CONFIG_FILE="$HOME/.gitconfig"

# Allowed orgs/repos for push (comma-separated)
ALLOWED_ORGS="aatos-git-collab,aatos,aatos-cloud"

#-------------------------------------------------------------------------------
# Colors
#-------------------------------------------------------------------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
error()   { echo -e "${RED}[ERROR]${NC} $1"; }

#-------------------------------------------------------------------------------
# Usage
#-------------------------------------------------------------------------------
usage() {
    cat << EOF
Git Push Safety Setup Script

Usage: $(basename "$0") [OPTIONS]

OPTIONS:
    --silent     Non-interactive mode (use defaults)
    --verify     Only verify existing setup, don't modify
    --uninstall  Remove all safety measures
    --help       Show this help

EXAMPLES:
    $(basename "$0")              # Interactive setup
    $(basename "$0") --silent    # Non-interactive
    $(basename "$0") --verify    # Check current setup
    $(basename "$0") --uninstall # Remove safety measures

EOF
    exit 0
}

#-------------------------------------------------------------------------------
# Create Pre-Push Hook
#-------------------------------------------------------------------------------
create_hook() {
    info "Creating pre-push hook..."
    
    mkdir -p "$HOOKS_DIR"
    
    cat > "$HOOK_FILE" << 'EOFHOOK'
#!/bin/bash
# Global pre-push hook - prevents accidental pushes to non-aatos repos AND public repos
# Generated by git-push-safety.sh

# Allowed owners/orgs for push (configured at install time)
ALLOWED_ORGS="__ALLOWED_ORGS__"

# Get the remote being pushed to
REMOTE_URL=$(git remote get-url --push origin 2>/dev/null)

# If no push URL configured, try fetch URL
if [ -z "$REMOTE_URL" ] || [ "$REMOTE_URL" = "(no pushurl)" ]; then
    REMOTE_URL=$(git remote get-url origin 2>/dev/null)
fi

# Check if pushurl is set to NO_PUSH_ALLOWED (fetch-only remotes)
if [ "$REMOTE_URL" = "NO_PUSH_ALLOWED" ]; then
    echo "ERROR: Push to this remote is disabled (NO_PUSH_ALLOWED)"
    echo "This remote is configured as fetch-only."
    exit 1
fi

# Check if pushing to allowed orgs AND private repo
if [ -n "$REMOTE_URL" ]; then
    ALLOWED=false
    IS_PRIVATE=false
    IFS=',' read -ra ORG_ARRAY <<< "$ALLOWED_ORGS"
    for org in "${ORG_ARRAY[@]}"; do
        if echo "$REMOTE_URL" | grep -qi "$org"; then
            ALLOWED=true
            break
        fi
    done

    if [ "$ALLOWED" = "false" ]; then
        echo "ERROR: Push to non-aatos repo is blocked!" >&2
        echo "" >&2
        echo "Push URL: $REMOTE_URL" >&2
        echo "Allowed orgs: $ALLOWED_ORGS" >&2
        echo "" >&2
        echo "To temporarily bypass:" >&2
        echo "  git config --global --unset core.hooksPath" >&2
        echo "  # then push" >&2
        echo "  git config --global core.hooksPath ~/.git-hooks" >&2
        exit 1
    fi

    # === PRIVATE REPO CHECK ===
    # Extract org/repo from URL for GitHub API check
    if echo "$REMOTE_URL" | grep -qE "github.com[/:]([^/]+)/([^/]+?)(?:\.git)?$"; then
        # Normalize: git@github.com:org/repo.git or https://github.com/org/repo
        REPO_PATH=$(echo "$REMOTE_URL" | sed -E 's/.*github.com[/:]([^/]+)\/([^/]+?)(?:\.git)?$/\1\/\2/')
        # Try unauthenticated API — public repos return 200, private repos return 404
        HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "https://api.github.com/repos/$REPO_PATH" 2>/dev/null || echo "000")
        if [ "$HTTP_CODE" = "200" ]; then
            # Repo is publicly accessible — block it
            IS_PRIVATE=false
        elif [ "$HTTP_CODE" = "404" ]; then
            # Could be private (requires auth) or doesn't exist
            # Check via SSH if available, otherwise assume private (safe default)
            if ssh -o BatchMode=yes -o ConnectTimeout=5 git@github.com 2>&1 | grep -q "successfully authenticated" 2>/dev/null; then
                # Authenticated to GitHub — check properly via API
                GH_TOKEN=$(git config --global --get github.token 2>/dev/null || echo '')
                if [ -n "$GH_TOKEN" ]; then
                    GH_RESPONSE=$(curl -s -H "Authorization: token $GH_TOKEN" \
                        "https://api.github.com/repos/$REPO_PATH" 2>/dev/null)
                    if echo "$GH_RESPONSE" | grep -q '"private": true'; then
                        IS_PRIVATE=true
                    elif echo "$GH_RESPONSE" | grep -q '"private": false'; then
                        IS_PRIVATE=false
                    fi
                else
                    # No token but SSH works — try gh CLI
                    if command -v gh &>/dev/null && gh auth status &>/dev/null; then
                        GH_RESPONSE=$(gh api "repos/$REPO_PATH" 2>/dev/null || echo '{}')
                        if echo "$GH_RESPONSE" | grep -q '"private": true'; then
                            IS_PRIVATE=true
                        elif echo "$GH_RESPONSE" | grep -q '"private": false'; then
                            IS_PRIVATE=false
                        fi
                    else
                        # No token, no gh, SSH auth to GH — assume private (safe default)
                        IS_PRIVATE=true
                    fi
                fi
            else
                # Not authenticated to GH via SSH — assume private (safe default)
                IS_PRIVATE=true
            fi
        fi
    else
        # Non-GitHub URL (e.g., self-hosted) — skip API check, trust org check
        IS_PRIVATE=true
    fi

    if [ "$IS_PRIVATE" = "false" ]; then
        echo "ERROR: Push to PUBLIC repo is blocked!" >&2
        echo "" >&2
        echo "Push URL: $REMOTE_URL" >&2
        echo "Reason: Only PRIVATE repos are allowed to be pushed to." >&2
        echo "" >&2
        echo "To temporarily bypass:" >&2
        echo "  git config --global --unset core.hooksPath" >&2
        echo "  # then push" >&2
        echo "  git config --global core.hooksPath ~/.git-hooks" >&2
        exit 1
    fi
fi

exit 0
EOFHOOK

    # Replace placeholder with actual allowed orgs
    sed -i "s/__ALLOWED_ORGS__/$ALLOWED_ORGS/g" "$HOOK_FILE"
    
    chmod +x "$HOOK_FILE"
    success "Created: $HOOK_FILE"
}

#-------------------------------------------------------------------------------
# Configure Global Git Settings
#-------------------------------------------------------------------------------
configure_git() {
    info "Configuring global git settings..."
    
    # Set global hooks path
    git config --global core.hooksPath "$HOOKS_DIR"
    
    # Set safe push default
    git config --global push.default current
    git config --global push.followTags false
    
    success "Git global settings configured"
}

#-------------------------------------------------------------------------------
# Set Up New Repo (optional - for current directory)
#-------------------------------------------------------------------------------
setup_current_repo() {
    if [ ! -d ".git" ]; then
        warn "Not in a git repository. Skipping repo setup."
        return
    fi
    
    info "Setting up current repository..."
    
    # Ensure origin push URL is set (only if origin exists)
    if git remote get-url origin &>/dev/null; then
        CURRENT_ORIGIN=$(git remote get-url origin)
        
        # If it's a coollabsio repo, add our fork as origin
        if echo "$CURRENT_ORIGIN" | grep -q "coollabsio/coolify"; then
            warn "Detected coollabsio/coolify - this is the upstream repo"
            warn "You may want to set origin to your fork instead"
        fi
    fi
    
    # Check if upstream exists and set pushurl to NO_PUSH_ALLOWED
    if git remote get-url upstream &>/dev/null; then
        info "Setting upstream to fetch-only..."
        git remote set-url --push upstream NO_PUSH_ALLOWED
        success "Upstream remote is now fetch-only"
    fi
    
    success "Repository configured"
}

#-------------------------------------------------------------------------------
# Verify Setup
#-------------------------------------------------------------------------------
verify_setup() {
    echo ""
    echo "=========================================="
    echo -e "${BLUE}Git Push Safety Verification${NC}"
    echo "=========================================="
    echo ""
    
    local errors=0
    
    # Check hook file
    echo "1. Pre-Push Hook:"
    if [ -f "$HOOK_FILE" ]; then
        if [ -x "$HOOK_FILE" ]; then
            success "  $HOOK_FILE (executable)"
        else
            error "  $HOOK_FILE (not executable)"
            errors=$((errors + 1))
        fi
        
        # Check allowed orgs in hook
        HOOK_ORGS=$(grep 'ALLOWED_ORGS=' "$HOOK_FILE" | head -1 | sed 's/.*="\(.*\)"/\1/')
        echo "  Allowed orgs: $HOOK_ORGS"
    else
        error "  $HOOK_FILE (not found)"
        errors=$((errors + 1))
    fi
    
    # Check global config
    echo ""
    echo "2. Global Git Config:"
    HOOKSPATH=$(git config --global --get core.hooksPath 2>/dev/null || echo "(not set)")
    if [ "$HOOKSPATH" = "$HOOKS_DIR" ]; then
        success "  core.hooksPath = $HOOKSPATH"
    else
        error "  core.hooksPath = $HOOKSPATH (expected: $HOOKS_DIR)"
        errors=$((errors + 1))
    fi
    
    PUSH_DEFAULT=$(git config --global --get push.default 2>/dev/null || echo "(not set)")
    echo "  push.default = $PUSH_DEFAULT"
    
    # Check current repo if in one
    echo ""
    echo "3. Current Repository:"
    if [ -d ".git" ]; then
        echo "  $(pwd) - Git repository detected"
        
        # Check remotes
        for remote in $(git remote); do
            FETCH_URL=$(git remote get-url "$remote")
            PUSH_URL=$(git remote get-url --push "$remote" 2>/dev/null || echo "(none)")
            
            if [ "$PUSH_URL" = "NO_PUSH_ALLOWED" ]; then
                success "  $remote: fetch-only"
            elif echo "$PUSH_URL" | grep -q "aatos"; then
                success "  $remote: push allowed"
            else
                warn "  $remote: $PUSH_URL"
            fi
        done
    else
        echo "  (not in a git repository)"
    fi
    
    echo ""
    echo "=========================================="
    if [ $errors -eq 0 ]; then
        success "All safety measures in place!"
    else
        error "$errors issue(s) found"
    fi
    echo "=========================================="
    
    return $errors
}

#-------------------------------------------------------------------------------
# Uninstall
#-------------------------------------------------------------------------------
uninstall() {
    info "Removing Git Push Safety..."
    
    # Remove hook
    if [ -f "$HOOK_FILE" ]; then
        rm -f "$HOOK_FILE"
        success "Removed: $HOOK_FILE"
    fi
    
    # Remove from global config
    git config --global --unset core.hooksPath 2>/dev/null || true
    
    success "Git Push Safety uninstalled"
}

#-------------------------------------------------------------------------------
# Main
#-------------------------------------------------------------------------------
main() {
    local mode="install"
    
    # Parse arguments
    for arg in "$@"; do
        case $arg in
            --silent)  SILENT=true ;;
            --verify)  mode="verify" ;;
            --uninstall) mode="uninstall" ;;
            --help)    usage ;;
        esac
    done
    
    case $mode in
        verify)
            verify_setup
            ;;
        uninstall)
            uninstall
            ;;
        install)
            echo ""
            echo "=========================================="
            echo -e "${BLUE}Git Push Safety Setup${NC}"
            echo "=========================================="
            echo ""
            echo "This script will set up:"
            echo "  1. Pre-push hook: ~/.git-hooks/pre-push"
            echo "  2. Global git config: core.hooksPath"
            echo "  3. Block pushes to non-aatos repos"
            echo ""
            echo "Allowed orgs: $ALLOWED_ORGS"
            echo ""
            
            if [ "$SILENT" != "true" ]; then
                read -p "Continue? [Y/n] " -n 1 -r
                echo
                if [[ ! $REPLY =~ ^[Yy]$ ]] && [[ ! -z $REPLY ]]; then
                    echo "Cancelled."
                    exit 0
                fi
            fi
            
            create_hook
            configure_git
            setup_current_repo
            
            echo ""
            success "Git Push Safety installed!"
            echo ""
            echo "To verify: bash $0 --verify"
            ;;
    esac
}

main "$@"
